import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'locale_controller.dart';

class AppLocalizations {
  AppLocalizations(this.languageCode);

  final String languageCode;

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'trending_today': 'Trending today',
      'trending_this_week': 'Trending this week',
      'now_playing': 'Now playing',
      'continue_watching': 'Continue watching',
      'watchlist_preview': 'Watchlist preview',
      'picks_for_you': 'More like your recent picks',
      'discover': 'Discover',
      'movies': 'Movies',
      'tv_shows': 'TV Shows',
      'search': 'Search',
      'search_library': 'Search the CineTrekker library.',
      'load_more': 'Load more',
      'library': 'Library',
      'watchlist': 'Watchlist',
      'watched': 'Watched',
      'tv_tracking': 'TV tracking',
      'profile': 'Profile',
      'collections': 'Collections',
      'achievements': 'Achievements',
      'year_in_review': 'Year in review',
      'favorites': 'Favorites',
      'settings': 'Settings',
      'app_theme': 'App theme',
      'app_language': 'App language',
      'maturity_rating': 'Maturity rating',
      'text_scaling': 'Text scaling',
      'delete_account': 'Delete account',
      'export_data': 'Export data',
      'sign_out': 'Sign out',
      'comments': 'Comments',
      'add_comment': 'Add a comment',
      'contains_spoiler': 'Contains spoiler',
      'post': 'Post',
      'sign_in_comments': 'Sign in to post comments and like other replies.',
      'your_rating': 'Your rating',
      'save_rating': 'Save rating',
      'follow_show': 'Follow show',
      'unfollow_show': 'Unfollow show',
      'mark_episode_watched': 'Mark episode watched',
      'in_theaters': 'In Theaters',
    },
    'es': {
      'trending_today': 'Tendencias de hoy',
      'trending_this_week': 'Tendencias de esta semana',
      'now_playing': 'En cartelera',
      'continue_watching': 'Seguir viendo',
      'watchlist_preview': 'Vista previa de lista',
      'picks_for_you': 'Más recomendaciones para ti',
      'discover': 'Descubrir',
      'movies': 'Películas',
      'tv_shows': 'Series de TV',
      'search': 'Buscar',
      'search_library': 'Buscar en la biblioteca de CineTrekker.',
      'load_more': 'Cargar más',
      'library': 'Biblioteca',
      'watchlist': 'Por ver',
      'watched': 'Visto',
      'tv_tracking': 'Seguimiento de TV',
      'profile': 'Perfil',
      'collections': 'Colecciones',
      'achievements': 'Logros',
      'year_in_review': 'Resumen del año',
      'favorites': 'Favoritos',
      'settings': 'Ajustes',
      'app_theme': 'Tema de la app',
      'app_language': 'Idioma de la app',
      'maturity_rating': 'Clasificación de edad',
      'text_scaling': 'Escala de texto',
      'delete_account': 'Eliminar cuenta',
      'export_data': 'Exportar datos',
      'sign_out': 'Cerrar sesión',
      'comments': 'Comentarios',
      'add_comment': 'Añadir un comentario',
      'contains_spoiler': 'Contiene spoilers',
      'post': 'Publicar',
      'sign_in_comments': 'Inicia sesión para comentar y dar me gusta.',
      'your_rating': 'Tu calificación',
      'save_rating': 'Guardar calificación',
      'follow_show': 'Seguir serie',
      'unfollow_show': 'Dejar de seguir',
      'mark_episode_watched': 'Marcar episodio visto',
      'in_theaters': 'En cartelera',
    },
    'fr': {
      'trending_today': 'Tendances aujourd\'hui',
      'trending_this_week': 'Tendances cette semaine',
      'now_playing': 'Actuellement au cinéma',
      'continue_watching': 'Reprendre la lecture',
      'watchlist_preview': 'Aperçu de la liste',
      'picks_for_you': 'Plus de suggestions pour vous',
      'discover': 'Découvrir',
      'movies': 'Films',
      'tv_shows': 'Séries TV',
      'search': 'Rechercher',
      'search_library': 'Rechercher dans CineTrekker.',
      'load_more': 'Charger plus',
      'library': 'Bibliothèque',
      'watchlist': 'À voir',
      'watched': 'Vu',
      'tv_tracking': 'Suivi des séries',
      'profile': 'Profil',
      'collections': 'Collections',
      'achievements': 'Succès',
      'year_in_review': 'Rétrospective de l\'année',
      'favorites': 'Favoris',
      'settings': 'Paramètres',
      'app_theme': 'Thème de l\'application',
      'app_language': 'Langue de l\'application',
      'maturity_rating': 'Classification d\'âge',
      'text_scaling': 'Taille du texte',
      'delete_account': 'Supprimer le compte',
      'export_data': 'Exporter les données',
      'sign_out': 'Se déconnecter',
      'comments': 'Commentaires',
      'add_comment': 'Ajouter un commentaire',
      'contains_spoiler': 'Contient des spoilers',
      'post': 'Publier',
      'sign_in_comments': 'Connectez-vous pour ajouter un commentaire.',
      'your_rating': 'Votre note',
      'save_rating': 'Enregistrer la note',
      'follow_show': 'Suivre la série',
      'unfollow_show': 'Ne plus suivre',
      'mark_episode_watched': 'Marquer comme vu',
      'in_theaters': 'À l\'affiche',
    },
    'de': {
      'trending_today': 'Heute im Trend',
      'trending_this_week': 'Diese Woche im Trend',
      'now_playing': 'Aktuelle Filme',
      'continue_watching': 'Weitersehen',
      'watchlist_preview': 'Watchlist-Vorschau',
      'picks_for_you': 'Mehr Empfehlungen für dich',
      'discover': 'Entdecken',
      'movies': 'Filme',
      'tv_shows': 'Serien',
      'search': 'Suchen',
      'search_library': 'CineTrekker durchsuchen.',
      'load_more': 'Mehr laden',
      'library': 'Bibliothek',
      'watchlist': 'Watchlist',
      'watched': 'Gesehen',
      'tv_tracking': 'Serien-Verfolgung',
      'profile': 'Profil',
      'collections': 'Sammlungen',
      'achievements': 'Erfolge',
      'year_in_review': 'Jahresrückblick',
      'favorites': 'Favoriten',
      'settings': 'Einstellungen',
      'app_theme': 'App-Design',
      'app_language': 'App-Sprache',
      'maturity_rating': 'Altersfreigabe',
      'text_scaling': 'Textgröße',
      'delete_account': 'Konto löschen',
      'export_data': 'Daten exportieren',
      'sign_out': 'Abmelden',
      'comments': 'Kommentare',
      'add_comment': 'Einen Kommentar schreiben',
      'contains_spoiler': 'Enthält Spoiler',
      'post': 'Posten',
      'sign_in_comments': 'Melde dich an, um Kommentare zu schreiben.',
      'your_rating': 'Deine Bewertung',
      'save_rating': 'Bewertung speichern',
      'follow_show': 'Serie folgen',
      'unfollow_show': 'Entfolgen',
      'mark_episode_watched': 'Episode als gesehen markieren',
      'in_theaters': 'Im Kino',
    },
    'tr': {
      'trending_today': 'Bugün trendde olanlar',
      'trending_this_week': 'Bu hafta trendde olanlar',
      'now_playing': 'Vizyondakiler',
      'continue_watching': 'İzlemeye devam et',
      'watchlist_preview': 'İzleme listesi önizlemesi',
      'picks_for_you': 'Sizin için önerilenler',
      'discover': 'Keşfet',
      'movies': 'Filmler',
      'tv_shows': 'Diziler',
      'search': 'Ara',
      'search_library': 'CineTrekker kütüphanesinde ara.',
      'load_more': 'Daha fazla yükle',
      'library': 'Kütüphane',
      'watchlist': 'İzleme Listesi',
      'watched': 'İzlenenler',
      'tv_tracking': 'Dizi Takibi',
      'profile': 'Profil',
      'collections': 'Koleksiyonlar',
      'achievements': 'Başarılar',
      'year_in_review': 'Yılın Özeti',
      'favorites': 'Favoriler',
      'settings': 'Ayarlar',
      'app_theme': 'Uygulama teması',
      'app_language': 'Uygulama dili',
      'maturity_rating': 'Yaş sınırı',
      'text_scaling': 'Metin boyutu',
      'delete_account': 'Hesabı sil',
      'export_data': 'Verileri dışa aktar',
      'sign_out': 'Çıkış yap',
      'comments': 'Yorumlar',
      'add_comment': 'Yorum ekle',
      'contains_spoiler': 'Sürprizbozan (spoiler) içerir',
      'post': 'Gönder',
      'sign_in_comments': 'Yorum yazmak ve beğenmek için giriş yapın.',
      'your_rating': 'Puanınız',
      'save_rating': 'Puanı kaydet',
      'follow_show': 'Diziyi takip et',
      'unfollow_show': 'Takibi bırak',
      'mark_episode_watched': 'Bölümü izlendi olarak işaretle',
      'in_theaters': 'Vizyonda',
    },
    'ar': {
      'trending_today': 'شائع اليوم',
      'trending_this_week': 'شائع هذا الأسبوع',
      'now_playing': 'يعرض حالياً',
      'continue_watching': 'متابعة المشاهدة',
      'watchlist_preview': 'معاينة قائمة المشاهدة',
      'picks_for_you': 'المزيد من اقتراحاتنا لك',
      'discover': 'اكتشف',
      'movies': 'أفلام',
      'tv_shows': 'مسلسلات',
      'search': 'بحث',
      'search_library': 'البحث في مكتبة CineTrekker.',
      'load_more': 'تحميل المزيد',
      'library': 'المكتبة',
      'watchlist': 'قائمة المشاهدة',
      'watched': 'تمت مشاهدته',
      'tv_tracking': 'تتبع المسلسلات',
      'profile': 'الملف الشخصي',
      'collections': 'المجموعات',
      'achievements': 'الإنجازات',
      'year_in_review': 'حصاد العام',
      'favorites': 'المفضلة',
      'settings': 'الإعدادات',
      'app_theme': 'سمة التطبيق',
      'app_language': 'لغة التطبيق',
      'maturity_rating': 'التصنيف العمري',
      'text_scaling': 'تكبير الخط',
      'delete_account': 'حذف الحساب',
      'export_data': 'تصدير البيانات',
      'sign_out': 'تسجيل الخروج',
      'comments': 'التعليقات',
      'add_comment': 'إضافة تعليق',
      'contains_spoiler': 'يحتوي على حرق للأحداث',
      'post': 'نشر',
      'sign_in_comments': 'سجل الدخول لإضافة تعليق والتفاعل مع الآخرين.',
      'your_rating': 'تقييمك',
      'save_rating': 'حفظ التقييم',
      'follow_show': 'متابعة المسلسل',
      'unfollow_show': 'إلغاء المتابعة',
      'mark_episode_watched': 'تحديد الحلقة كـمشاهدة',
      'in_theaters': 'في دور العرض',
    },
  };

  String translate(String key) {
    final languageMap =
        _localizedValues[languageCode] ?? _localizedValues['en']!;
    return languageMap[key] ?? key;
  }
}

final appLocalizationsProvider = Provider<AppLocalizations>((ref) {
  final localeStyle = ref.watch(localeControllerProvider);
  final systemLocale = WidgetsBinding.instance.platformDispatcher.locale;
  final code = tmdbLanguageCodeForLocaleStyle(
    localeStyle,
    systemLocale: systemLocale,
  );
  return AppLocalizations(code);
});
